### PR TITLE
Updated pt/amazon_alexa_skill.txt

### PR DESCRIPTION
**Pull request by ricardo-brenner**

### CODE REVIEW

**Comment by kakopappa** [comment]
Thanks. 

I will submit this for approval. let see how it goes. 

Let me know when you signup for Sinric Pro when the site goes live.

**Comment by ricardo-brenner** [comment]
I'll try to translate the other files till this weekend

**Comment by ricardo-brenner** [comment]
Signed up to pro, will start to move my devices this weekend

**Comment by ricardo-brenner** [comment]
I'm moving my devices do Pro, any chance to get one extra device for free? :)

**Pull request merged**
